# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66b89d04cadc9b0948f2ccc958087441"
application_url = "https://lcd-whereas-advisory-unemployment.trycloudflare.com"
embedded = true
name = "testapp"
handle = "testapp-3587"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lcd-whereas-advisory-unemployment.trycloudflare.com/auth/callback",
  "https://lcd-whereas-advisory-unemployment.trycloudflare.com/auth/shopify/callback",
  "https://lcd-whereas-advisory-unemployment.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
